apiVersion: v1
kind: Service
metadata:
  name: {{template "ldap" . }}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}-{{.Values.Master.Component}}"
spec:
  ports:
    - port: {{.Values.Master.LdapPort1}}
      name: ldap-1
      targetPort: {{.Values.Master.LdapPort1}}
    - port: {{.Values.Master.LdapPort2}}
      name: ldap-2
      targetPort: {{.Values.Master.LdapPort2}}
  selector:
    component: "{{.Release.Name}}-{{.Values.Master.Component}}"
  type: {{.Values.Master.ServiceType}}
