---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "init-db",
            "image": "mysql",
            "command": ["bash", "-c", "mysql -u root -p{{ .Values.global.mariadbRootPassword }} -h{{ template "database" . }} --verbose < /opt/gerrit/create-gerrit-db.sql"],
            "volumeMounts": [
              {
                "name": "gerrit-config",
                "mountPath": "/opt/gerrit"
              }
            ]
          }
      ]'
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["kaigara", "start", "gerrit-start.sh"]
        ports:
        - containerPort: {{ .Values.service.http.internalPort }}
          name: http
        - containerPort: {{ .Values.service.ssh.internalPort }}
          name: ssh
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
          - mountPath: "/var/gerrit/review_site"
            name: gerrit-site
          - mountPath: "/etc/kaigara/metadata"
            name: gerrit-config
      volumes:
      - name: gerrit-config
        configMap:
          name: {{ template "fullname" . }}
      - name: gerrit-site
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "fullname" . }}
      {{- else }}
        emptyDir: {}
      {{- end -}}
